version: "3"
services:
  mysqld:
    restart: always
    image: mysql:5.7.22
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=microservices
    volumes:
    - yuntan-mysql:/var/lib/mysql
  simple-gateway:
    restart: always
    image: simple-gateway:yuntan-build
    depends_on:
    - mysqld
    ports:
    - '13000:13000'
  yuntan-mqtt:
    restart: always
    image: yuntan-mqtt:yuntan-build
    depends_on:
    - simple-gateway
    environment:
    - HOST=http://simple-gateway:13000
    - KEY=303a7f6361985d1eb891
    - SECRET=fb943942efea9aeb2cccd0b8c0698955f288a091ec2368e8c133860b742ffdcf
    ports:
    - '1883:1883'
  coin:
    restart: always
    image: coin:yuntan-build
    depends_on:
    - mysqld
    environment:
    - TABLE_PREFIX=47d4ad028e6deab9a59f
  yuntan-user:
    restart: always
    image: yuntan-user:yuntan-build
    depends_on:
    - mysqld
    environment:
    - TABLE_PREFIX=303a7f6361985d1eb891
  yuntan-article:
    restart: always
    image: yuntan-article:yuntan-build
    depends_on:
    - mysqld
    environment:
    - TABLE_PREFIX=8d8c6771e70ff06c95c5

volumes:
  yuntan-mysql:
